server:
  port: 8080

spring:
  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://20.163.164.200:3306/homework?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: CustomerX
    password: CustX10086.
